name: Test-And-Publish
on: 
    workflow_dispatch:
env:
  XCODE_VERSION: '16.1.0'
  JAVA_VERSION: '21'
jobs:
     
  deploy:
    name: Deploy Library
    #runs-on: macos-13, self-hosted
    runs-on: macos-15
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      PUBLISH: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Publish Library
        run: |
          echo "Publishing and Releasing library 🚀"
          ./gradlew publish
